/* ============================================================
   PANDOMİM KART VERİ BANKASI
   Her öğe: { name, emoji, taboo: [yasaklı kelimeler] }
   ============================================================ */

const CATEGORIES = {

  hayvanlar: { label:'🐾 Hayvanlar', items:[
    {name:'Kedi', emoji:'🐱', taboo:['Miyav','Pati','Evcil']},
    {name:'Köpek', emoji:'🐶', taboo:['Hav','Havlar','Sadık']},
    {name:'Aslan', emoji:'🦁', taboo:['Yele','Kükrer','Kral']},
    {name:'Kaplan', emoji:'🐯', taboo:['Çizgili','Kükrer','Vahşi']},
    {name:'Fil', emoji:'🐘', taboo:['Hortum','Kocaman','Afrika']},
    {name:'Zürafa', emoji:'🦒', taboo:['Uzun Boyun','Benekli','Afrika']},
    {name:'Maymun', emoji:'🐒', taboo:['Muz','Ağaç','Sırıtır']},
    {name:'Ayı', emoji:'🐻', taboo:['Bal','Kış Uykusu','Pati']},
    {name:'Kurt', emoji:'🐺', taboo:['Uluma','Sürü','Vahşi']},
    {name:'Tilki', emoji:'🦊', taboo:['Kurnaz','Kızıl','Kuyruk']},
    {name:'Tavşan', emoji:'🐰', taboo:['Havuç','Zıplar','Kulak']},
    {name:'Fare', emoji:'🐭', taboo:['Peynir','Küçük','Kemirir']},
    {name:'At', emoji:'🐴', taboo:['Nal','Eyer','Koşar']},
    {name:'İnek', emoji:'🐮', taboo:['Süt','Böğürür','Çiftlik']},
    {name:'Koyun', emoji:'🐑', taboo:['Yün','Meleme','Çoban']},
    {name:'Keçi', emoji:'🐐', taboo:['Sakal','Meleme','Dağ']},
    {name:'Domuz', emoji:'🐷', taboo:['Çamur','Homur','Çiftlik']},
    {name:'Tavuk', emoji:'🐔', taboo:['Yumurta','Gıdaklar','Çiftlik']},
    {name:'Horoz', emoji:'🐓', taboo:['Öter','Sabah','İbik']},
    {name:'Ördek', emoji:'🦆', taboo:['Vak Vak','Gölet','Perde Ayak']},
    {name:'Kuş', emoji:'🐦', taboo:['Uçar','Kanat','Öter']},
    {name:'Baykuş', emoji:'🦉', taboo:['Gece','Gözlük','Ötmek']},
    {name:'Papağan', emoji:'🦜', taboo:['Konuşur','Renkli','Kafes']},
    {name:'Balık', emoji:'🐟', taboo:['Yüzer','Solungaç','Su']},
    {name:'Köpekbalığı', emoji:'🦈', taboo:['Diş','Okyanus','Tehlikeli']},
    {name:'Yunus', emoji:'🐬', taboo:['Zeki','Okyanus','Zıplar']},
    {name:'Balina', emoji:'🐳', taboo:['Kocaman','Okyanus','Memeli']},
    {name:'Ahtapot', emoji:'🐙', taboo:['Sekiz Kol','Mürekkep','Deniz']},
    {name:'Yılan', emoji:'🐍', taboo:['Zehir','Sürünür','Dil']},
    {name:'Kaplumbağa', emoji:'🐢', taboo:['Kabuk','Yavaş','Uzun Ömür']},
    {name:'Kertenkele', emoji:'🦎', taboo:['Kuyruk','Sürünen','Kaya']},
    {name:'Timsah', emoji:'🐊', taboo:['Diş','Nehir','Pullu']},
    {name:'Kurbağa', emoji:'🐸', taboo:['Zıplar','Vır Vır','Gölet']},
    {name:'Örümcek', emoji:'🕷️', taboo:['Ağ','Sekiz Bacak','Zehir']},
    {name:'Arı', emoji:'🐝', taboo:['Bal','Vızıldar','İğne']},
    {name:'Kelebek', emoji:'🦋', taboo:['Kanat','Renkli','Uçar']},
    {name:'Karınca', emoji:'🐜', taboo:['Küçük','Koloni','Çalışkan']},
    {name:'Penguen', emoji:'🐧', taboo:['Kutup','Frak','Buz']},
    {name:'Deve', emoji:'🐫', taboo:['Hörgüç','Çöl','Susuz']},
    {name:'Kanguru', emoji:'🦘', taboo:['Cep','Sıçrar','Avustralya']},
    {name:'Panda', emoji:'🐼', taboo:['Siyah Beyaz','Bambu','Çin']},
    {name:'Koala', emoji:'🐨', taboo:['Okaliptüs','Avustralya','Ağaç']},
    {name:'Zebra', emoji:'🦓', taboo:['Çizgili','Afrika','At']},
    {name:'Geyik', emoji:'🦌', taboo:['Boynuz','Orman','Hızlı']},
    {name:'Sincap', emoji:'🐿️', taboo:['Fındık','Kuyruk','Ağaç']},
    {name:'Yarasa', emoji:'🦇', taboo:['Gece','Uçar','Mağara']},
    {name:'Flamingo', emoji:'🦩', taboo:['Pembe','Tek Ayak','Göl']},
    {name:'Fok', emoji:'🦭', taboo:['Yüzgeç','Okyanus','Buz']},
    {name:'Karga', emoji:'🐦‍⬛', taboo:['Siyah','Öter','Kurnaz']}
  ]},

  esyalar: { label:'📦 Eşyalar', items:[
    {name:'Masa', emoji:'🪑', taboo:['Ayak','Ev','Mobilya']},
    {name:'Sandalye', emoji:'🪑', taboo:['Oturmak','Ayak','Mobilya']},
    {name:'Kitap', emoji:'📖', taboo:['Sayfa','Okumak','Yazar']},
    {name:'Kalem', emoji:'✏️', taboo:['Yazmak','Uç','Silgi']},
    {name:'Telefon', emoji:'📱', taboo:['Aramak','Ekran','Mesaj']},
    {name:'Bilgisayar', emoji:'💻', taboo:['Ekran','Klavye','İnternet']},
    {name:'Televizyon', emoji:'📺', taboo:['Ekran','Kanal','İzlemek']},
    {name:'Saat', emoji:'⏰', taboo:['Zaman','Kol','Alarm']},
    {name:'Ayna', emoji:'🪞', taboo:['Yansıma','Görmek','Cam']},
    {name:'Çanta', emoji:'👜', taboo:['Taşımak','Kayış','Okul']},
    {name:'Anahtar', emoji:'🔑', taboo:['Kapı','Kilit','Açmak']},
    {name:'Kapı', emoji:'🚪', taboo:['Açmak','Kapamak','Ev']},
    {name:'Pencere', emoji:'🪟', taboo:['Cam','Açmak','Ev']},
    {name:'Lamba', emoji:'💡', taboo:['Işık','Ampul','Yanmak']},
    {name:'Yastık', emoji:'🛏️', taboo:['Uyumak','Yumuşak','Yatak']},
    {name:'Bardak', emoji:'🥤', taboo:['İçmek','Su','Cam']},
    {name:'Tabak', emoji:'🍽️', taboo:['Yemek','Yuvarlak','Mutfak']},
    {name:'Kaşık', emoji:'🥄', taboo:['Çorba','Yemek','Mutfak']},
    {name:'Çatal', emoji:'🍴', taboo:['Yemek','Diş','Mutfak']},
    {name:'Bıçak', emoji:'🔪', taboo:['Kesmek','Keskin','Mutfak']},
    {name:'Tencere', emoji:'🍲', taboo:['Pişirmek','Mutfak','Kapak']},
    {name:'Buzdolabı', emoji:'🧊', taboo:['Soğuk','Mutfak','Yiyecek']},
    {name:'Süpürge', emoji:'🧹', taboo:['Temizlik','Toz','Sap']},
    {name:'Makas', emoji:'✂️', taboo:['Kesmek','Kağıt','Keskin']},
    {name:'Şemsiye', emoji:'☂️', taboo:['Yağmur','Açmak','Islak']},
    {name:'Gözlük', emoji:'👓', taboo:['Görmek','Cam','Göz']},
    {name:'Cüzdan', emoji:'👛', taboo:['Para','Kart','Taşımak']},
    {name:'Ayakkabı', emoji:'👟', taboo:['Ayak','Giymek','Bağcık']},
    {name:'Şapka', emoji:'🎩', taboo:['Baş','Giymek','Kafa']},
    {name:'Eldiven', emoji:'🧤', taboo:['El','Giymek','Soğuk']},
    {name:'Halı', emoji:'🧶', taboo:['Yer','Ev','Desen']},
    {name:'Perde', emoji:'🪟', taboo:['Pencere','Kumaş','Ev']},
    {name:'Ütü', emoji:'👕', taboo:['Kumaş','Sıcak','Giysi']},
    {name:'Valiz', emoji:'🧳', taboo:['Seyahat','Taşımak','Tekerlek']},
    {name:'Balon', emoji:'🎈', taboo:['Uçmak','Şişirmek','Parti']},
    {name:'Mum', emoji:'🕯️', taboo:['Yanmak','Işık','Ateş']},
    {name:'Silgi', emoji:'🧽', taboo:['Kalem','Silmek','Kağıt']},
    {name:'Cetvel', emoji:'📏', taboo:['Ölçmek','Çizgi','Uzunluk']},
    {name:'Çekiç', emoji:'🔨', taboo:['Çivi','Vurmak','Tamir']},
    {name:'Fener', emoji:'🔦', taboo:['Işık','Karanlık','El']}
  ]},

  sehirler: { label:'🗺️ Türkiye Şehirleri', items:[
    {name:'Adana', emoji:'🗺️', taboo:['Kebap','Şehir']},
    {name:'Adıyaman', emoji:'🗺️', taboo:['Nemrut','Şehir']},
    {name:'Afyonkarahisar', emoji:'🗺️', taboo:['Kaymak','Şehir']},
    {name:'Ağrı', emoji:'🗺️', taboo:['Dağ','Şehir']},
    {name:'Amasya', emoji:'🗺️', taboo:['Elma','Şehir']},
    {name:'Ankara', emoji:'🗺️', taboo:['Başkent','Anıtkabir']},
    {name:'Antalya', emoji:'🗺️', taboo:['Deniz','Tatil']},
    {name:'Artvin', emoji:'🗺️', taboo:['Yayla','Şehir']},
    {name:'Aydın', emoji:'🗺️', taboo:['İncir','Şehir']},
    {name:'Balıkesir', emoji:'🗺️', taboo:['Zeytin','Şehir']},
    {name:'Bilecik', emoji:'🗺️', taboo:['Osmanlı','Şehir']},
    {name:'Bingöl', emoji:'🗺️', taboo:['Dağ','Şehir']},
    {name:'Bitlis', emoji:'🗺️', taboo:['Van Gölü','Şehir']},
    {name:'Bolu', emoji:'🗺️', taboo:['Orman','Aşçı']},
    {name:'Burdur', emoji:'🗺️', taboo:['Göl','Şehir']},
    {name:'Bursa', emoji:'🗺️', taboo:['İskender','Yeşil']},
    {name:'Çanakkale', emoji:'🗺️', taboo:['Boğaz','Savaş']},
    {name:'Çankırı', emoji:'🗺️', taboo:['Tuz','Şehir']},
    {name:'Çorum', emoji:'🗺️', taboo:['Leblebi','Şehir']},
    {name:'Denizli', emoji:'🗺️', taboo:['Pamukkale','Horoz']},
    {name:'Diyarbakır', emoji:'🗺️', taboo:['Karpuz','Sur']},
    {name:'Edirne', emoji:'🗺️', taboo:['Selimiye','Sınır']},
    {name:'Elazığ', emoji:'🗺️', taboo:['Baraj','Şehir']},
    {name:'Erzincan', emoji:'🗺️', taboo:['Deprem','Şehir']},
    {name:'Erzurum', emoji:'🗺️', taboo:['Cağ Kebabı','Kar']},
    {name:'Eskişehir', emoji:'🗺️', taboo:['Öğrenci','Lületaşı']},
    {name:'Gaziantep', emoji:'🗺️', taboo:['Baklava','Fıstık']},
    {name:'Giresun', emoji:'🗺️', taboo:['Fındık','Şehir']},
    {name:'Gümüşhane', emoji:'🗺️', taboo:['Maden','Şehir']},
    {name:'Hakkari', emoji:'🗺️', taboo:['Dağ','Sınır']},
    {name:'Hatay', emoji:'🗺️', taboo:['Künefe','Mutfak']},
    {name:'Isparta', emoji:'🗺️', taboo:['Gül','Şehir']},
    {name:'Mersin', emoji:'🗺️', taboo:['Tantuni','Liman']},
    {name:'İstanbul', emoji:'🗺️', taboo:['Boğaz','Ayasofya']},
    {name:'İzmir', emoji:'🗺️', taboo:['Ege','Kordon']},
    {name:'Kars', emoji:'🗺️', taboo:['Kaşar','Kar']},
    {name:'Kastamonu', emoji:'🗺️', taboo:['Bakır','Şehir']},
    {name:'Kayseri', emoji:'🗺️', taboo:['Pastırma','Erciyes']},
    {name:'Kırklareli', emoji:'🗺️', taboo:['Şarap','Şehir']},
    {name:'Kırşehir', emoji:'🗺️', taboo:['Ahilik','Şehir']},
    {name:'Kocaeli', emoji:'🗺️', taboo:['Sanayi','İzmit']},
    {name:'Konya', emoji:'🗺️', taboo:['Mevlana','Etli Ekmek']},
    {name:'Kütahya', emoji:'🗺️', taboo:['Çini','Şehir']},
    {name:'Malatya', emoji:'🗺️', taboo:['Kayısı','Şehir']},
    {name:'Manisa', emoji:'🗺️', taboo:['Mesir','Üzüm']},
    {name:'Kahramanmaraş', emoji:'🗺️', taboo:['Dondurma','Şehir']},
    {name:'Mardin', emoji:'🗺️', taboo:['Taş Ev','Sabun']},
    {name:'Muğla', emoji:'🗺️', taboo:['Bodrum','Deniz']},
    {name:'Muş', emoji:'🗺️', taboo:['Ova','Şehir']},
    {name:'Nevşehir', emoji:'🗺️', taboo:['Kapadokya','Balon']},
    {name:'Niğde', emoji:'🗺️', taboo:['Elma','Şehir']},
    {name:'Ordu', emoji:'🗺️', taboo:['Fındık','Karadeniz']},
    {name:'Rize', emoji:'🗺️', taboo:['Çay','Karadeniz']},
    {name:'Sakarya', emoji:'🗺️', taboo:['Nehir','Şehir']},
    {name:'Samsun', emoji:'🗺️', taboo:['Atatürk','Karadeniz']},
    {name:'Siirt', emoji:'🗺️', taboo:['Battaniye','Şehir']},
    {name:'Sinop', emoji:'🗺️', taboo:['Cezaevi','Karadeniz']},
    {name:'Sivas', emoji:'🗺️', taboo:['Kongre','Şehir']},
    {name:'Tekirdağ', emoji:'🗺️', taboo:['Köfte','Şehir']},
    {name:'Tokat', emoji:'🗺️', taboo:['Kebap','Şehir']},
    {name:'Trabzon', emoji:'🗺️', taboo:['Hamsi','Karadeniz']},
    {name:'Tunceli', emoji:'🗺️', taboo:['Munzur','Dağ']},
    {name:'Şanlıurfa', emoji:'🗺️', taboo:['Lahmacun','Balıklıgöl']},
    {name:'Uşak', emoji:'🗺️', taboo:['Halı','Şehir']},
    {name:'Van', emoji:'🗺️', taboo:['Kahvaltı','Göl']},
    {name:'Yozgat', emoji:'🗺️', taboo:['Testi Kebabı','Şehir']},
    {name:'Zonguldak', emoji:'🗺️', taboo:['Kömür','Maden']},
    {name:'Aksaray', emoji:'🗺️', taboo:['Tuz Gölü','Şehir']},
    {name:'Bayburt', emoji:'🗺️', taboo:['Kalkandere','Şehir']},
    {name:'Karaman', emoji:'🗺️', taboo:['Bakla','Şehir']},
    {name:'Kırıkkale', emoji:'🗺️', taboo:['Fabrika','Şehir']},
    {name:'Batman', emoji:'🗺️', taboo:['Petrol','Şehir']},
    {name:'Şırnak', emoji:'🗺️', taboo:['Sınır','Dağ']},
    {name:'Bartın', emoji:'🗺️', taboo:['Orman','Karadeniz']},
    {name:'Ardahan', emoji:'🗺️', taboo:['Yayla','Kar']},
    {name:'Iğdır', emoji:'🗺️', taboo:['Ova','Sınır']},
    {name:'Yalova', emoji:'🗺️', taboo:['Termal','Deniz']},
    {name:'Karabük', emoji:'🗺️', taboo:['Demir Çelik','Şehir']},
    {name:'Kilis', emoji:'🗺️', taboo:['Zeytinyağı','Sınır']},
    {name:'Osmaniye', emoji:'🗺️', taboo:['Yer Fıstığı','Şehir']},
    {name:'Düzce', emoji:'🗺️', taboo:['Orman','Şehir']}
  ]},

  yiyecekler: { label:'🍎 Yiyecekler', items:[
    {name:'Ekmek', emoji:'🍞', taboo:['Fırın','Un','Yemek']},
    {name:'Peynir', emoji:'🧀', taboo:['Süt','Sarı','Kahvaltı']},
    {name:'Zeytin', emoji:'🫒', taboo:['Yağ','Siyah','Kahvaltı']},
    {name:'Yumurta', emoji:'🥚', taboo:['Tavuk','Kahvaltı','Sarı']},
    {name:'Bal', emoji:'🍯', taboo:['Arı','Tatlı','Kahvaltı']},
    {name:'Tereyağı', emoji:'🧈', taboo:['Süt','Ekmek','Kahvaltı']},
    {name:'Pasta', emoji:'🍰', taboo:['Doğum Günü','Tatlı','Kat']},
    {name:'Kek', emoji:'🧁', taboo:['Fırın','Tatlı','Un']},
    {name:'Çikolata', emoji:'🍫', taboo:['Kakao','Tatlı','Kahverengi']},
    {name:'Dondurma', emoji:'🍨', taboo:['Soğuk','Tatlı','Yaz']},
    {name:'Pizza', emoji:'🍕', taboo:['İtalya','Peynir','Dilim']},
    {name:'Makarna', emoji:'🍝', taboo:['İtalya','Sos','Un']},
    {name:'Hamburger', emoji:'🍔', taboo:['Ekmek','Köfte','Fast Food']},
    {name:'Döner', emoji:'🥙', taboo:['Et','Ekmek','Türk']},
    {name:'Kebap', emoji:'🍢', taboo:['Et','Şiş','Türk']},
    {name:'Lahmacun', emoji:'🫓', taboo:['İnce','Kıyma','Türk']},
    {name:'Baklava', emoji:'🍮', taboo:['Fıstık','Şerbet','Tatlı']},
    {name:'Salata', emoji:'🥗', taboo:['Yeşillik','Sağlıklı','Sos']},
    {name:'Çorba', emoji:'🍲', taboo:['Sıcak','Kaşık','Kase']},
    {name:'Pilav', emoji:'🍚', taboo:['Pirinç','Yan Yemek','Türk']},
    {name:'Mercimek', emoji:'🥣', taboo:['Çorba','Kırmızı','Sarı']},
    {name:'Patates', emoji:'🥔', taboo:['Kızartma','Toprak','Yan Yemek']},
    {name:'Domates', emoji:'🍅', taboo:['Kırmızı','Salata','Sos']},
    {name:'Salatalık', emoji:'🥒', taboo:['Yeşil','Salata','Turşu']},
    {name:'Biber', emoji:'🫑', taboo:['Yeşil','Acı','Dolma']},
    {name:'Soğan', emoji:'🧅', taboo:['Ağlatır','Kokulu','Mutfak']},
    {name:'Sarımsak', emoji:'🧄', taboo:['Kokulu','Diş','Mutfak']},
    {name:'Elma', emoji:'🍎', taboo:['Kırmızı','Meyve','Ağaç']},
    {name:'Muz', emoji:'🍌', taboo:['Sarı','Meyve','Maymun']},
    {name:'Çilek', emoji:'🍓', taboo:['Kırmızı','Meyve','Tohum']},
    {name:'Karpuz', emoji:'🍉', taboo:['Yeşil','Kırmızı','Yaz']},
    {name:'Üzüm', emoji:'🍇', taboo:['Salkım','Meyve','Bağ']},
    {name:'Portakal', emoji:'🍊', taboo:['Turuncu','Meyve','C Vitamini']},
    {name:'Limon', emoji:'🍋', taboo:['Ekşi','Sarı','Meyve']},
    {name:'Kiraz', emoji:'🍒', taboo:['Kırmızı','Meyve','Çekirdek']},
    {name:'Şeftali', emoji:'🍑', taboo:['Tüylü','Meyve','Yaz']},
    {name:'Ananas', emoji:'🍍', taboo:['Tropikal','Meyve','Dikenli']},
    {name:'Kavun', emoji:'🍈', taboo:['Sarı','Meyve','Yaz']},
    {name:'İncir', emoji:'🌿', taboo:['Kurutulmuş','Meyve','Ağaç']},
    {name:'Nar', emoji:'🍎', taboo:['Kırmızı','Tane','Meyve']}
  ]},

  ulasim: { label:'🚗 Ulaşım Araçları', items:[
    {name:'Araba', emoji:'🚗', taboo:['Tekerlek','Yol','Sürmek']},
    {name:'Otobüs', emoji:'🚌', taboo:['Yolcu','Durak','Sürücü']},
    {name:'Uçak', emoji:'✈️', taboo:['Kanat','Havalimanı','Uçmak']},
    {name:'Tren', emoji:'🚆', taboo:['Ray','İstasyon','Vagon']},
    {name:'Gemi', emoji:'🚢', taboo:['Deniz','Liman','Yüzmek']},
    {name:'Bisiklet', emoji:'🚲', taboo:['Pedal','Tekerlek','Sürmek']},
    {name:'Motosiklet', emoji:'🏍️', taboo:['Tekerlek','Hız','Sürmek']},
    {name:'Kamyon', emoji:'🚚', taboo:['Yük','Sürücü','Büyük']},
    {name:'Taksi', emoji:'🚕', taboo:['Sarı','Sürücü','Ücret']},
    {name:'Metro', emoji:'🚇', taboo:['Yer Altı','Ray','İstasyon']},
    {name:'Tramvay', emoji:'🚊', taboo:['Ray','Şehir','Elektrik']},
    {name:'Helikopter', emoji:'🚁', taboo:['Pervane','Uçmak','Pilot']},
    {name:'Roket', emoji:'🚀', taboo:['Uzay','Ateş','Fırlamak']},
    {name:'Yat', emoji:'⛵', taboo:['Deniz','Yelken','Lüks']},
    {name:'Kano', emoji:'🛶', taboo:['Kürek','Su','Nehir']},
    {name:'Vapur', emoji:'⛴️', taboo:['Boğaz','Deniz','İskele']},
    {name:'Traktör', emoji:'🚜', taboo:['Tarla','Çiftçi','Sürmek']},
    {name:'Ambulans', emoji:'🚑', taboo:['Hasta','Siren','Acil']},
    {name:'İtfaiye Aracı', emoji:'🚒', taboo:['Yangın','Siren','Su']},
    {name:'Polis Arabası', emoji:'🚓', taboo:['Siren','Polis','Işık']},
    {name:'Bebek Arabası', emoji:'👶', taboo:['Bebek','İtmek','Tekerlek']},
    {name:'Paten', emoji:'⛸️', taboo:['Tekerlek','Ayak','Kaymak']},
    {name:'Teleferik', emoji:'🚡', taboo:['Dağ','Kablo','Havada']},
    {name:'Kaykay', emoji:'🛹', taboo:['Tekerlek','Ayak','Kaymak']}
  ]},

  meslekler: { label:'👷 Meslekler', items:[
    {name:'Doktor', emoji:'🩺', taboo:['Hastane','Tedavi','Hasta']},
    {name:'Öğretmen', emoji:'👩‍🏫', taboo:['Okul','Ders','Tahta']},
    {name:'Mühendis', emoji:'👷', taboo:['Proje','Hesap','İnşaat']},
    {name:'Avukat', emoji:'⚖️', taboo:['Mahkeme','Dava','Hukuk']},
    {name:'Polis', emoji:'👮', taboo:['Suç','Üniforma','Kanun']},
    {name:'İtfaiyeci', emoji:'🧑‍🚒', taboo:['Yangın','Su','Kurtarmak']},
    {name:'Aşçı', emoji:'👨‍🍳', taboo:['Mutfak','Yemek','Pişirmek']},
    {name:'Şoför', emoji:'🚗', taboo:['Araba','Sürmek','Yol']},
    {name:'Pilot', emoji:'👨‍✈️', taboo:['Uçak','Uçmak','Havalimanı']},
    {name:'Hemşire', emoji:'👩‍⚕️', taboo:['Hastane','İğne','Doktor']},
    {name:'Berber', emoji:'💈', taboo:['Saç','Makas','Kesmek']},
    {name:'Terzi', emoji:'🧵', taboo:['Kumaş','Dikiş','Giysi']},
    {name:'Marangoz', emoji:'🪚', taboo:['Ahşap','Çekiç','Mobilya']},
    {name:'Çiftçi', emoji:'🌾', taboo:['Tarla','Ekin','Traktör']},
    {name:'Balıkçı', emoji:'🎣', taboo:['Balık','Olta','Deniz']},
    {name:'Ressam', emoji:'🎨', taboo:['Fırça','Boya','Tuval']},
    {name:'Müzisyen', emoji:'🎸', taboo:['Enstrüman','Şarkı','Nota']},
    {name:'Yazar', emoji:'✍️', taboo:['Kitap','Kalem','Roman']},
    {name:'Gazeteci', emoji:'📰', taboo:['Haber','Röportaj','Gazete']},
    {name:'Fotoğrafçı', emoji:'📷', taboo:['Kamera','Resim','Çekmek']},
    {name:'Mimar', emoji:'📐', taboo:['Bina','Plan','İnşaat']},
    {name:'Eczacı', emoji:'💊', taboo:['İlaç','Eczane','Reçete']},
    {name:'Veteriner', emoji:'🐾', taboo:['Hayvan','Tedavi','Klinik']},
    {name:'Diş Hekimi', emoji:'🦷', taboo:['Diş','Ağız','Muayene']},
    {name:'Garson', emoji:'🍽️', taboo:['Restoran','Sipariş','Servis']},
    {name:'Kasap', emoji:'🥩', taboo:['Et','Bıçak','Dükkan']},
    {name:'Fırıncı', emoji:'🥖', taboo:['Ekmek','Fırın','Un']},
    {name:'Manav', emoji:'🥬', taboo:['Meyve','Sebze','Dükkan']},
    {name:'Elektrikçi', emoji:'🔌', taboo:['Kablo','Priz','Elektrik']},
    {name:'Tesisatçı', emoji:'🔧', taboo:['Su','Boru','Musluk']}
  ]},

  hareketler: { label:'🏃 Hareketler', items:[
    {name:'Koşmak', emoji:'🏃', taboo:['Hızlı','Ayak','Spor']},
    {name:'Yürümek', emoji:'🚶', taboo:['Ayak','Adım','Yavaş']},
    {name:'Zıplamak', emoji:'🤸', taboo:['Havaya','Ayak','Yukarı']},
    {name:'Uyumak', emoji:'😴', taboo:['Yatak','Göz','Gece']},
    {name:'Gülmek', emoji:'😂', taboo:['Ağız','Mutlu','Ses']},
    {name:'Ağlamak', emoji:'😢', taboo:['Göz Yaşı','Üzgün','Göz']},
    {name:'Yüzmek', emoji:'🏊', taboo:['Su','Havuz','Kol']},
    {name:'Dans Etmek', emoji:'💃', taboo:['Müzik','Ayak','Hareket']},
    {name:'Şarkı Söylemek', emoji:'🎤', taboo:['Ses','Müzik','Ağız']},
    {name:'Yemek Yemek', emoji:'🍽️', taboo:['Ağız','Çatal','Tabak']},
    {name:'Su İçmek', emoji:'🚰', taboo:['Bardak','Ağız','Susamak']},
    {name:'Kitap Okumak', emoji:'📖', taboo:['Sayfa','Göz','Harf']},
    {name:'Yazı Yazmak', emoji:'✍️', taboo:['Kalem','Kağıt','El']},
    {name:'Resim Yapmak', emoji:'🖌️', taboo:['Fırça','Boya','Kağıt']},
    {name:'Futbol Oynamak', emoji:'⚽', taboo:['Top','Ayak','Kale']},
    {name:'Basketbol Oynamak', emoji:'🏀', taboo:['Top','Pota','El']},
    {name:'Araba Sürmek', emoji:'🚗', taboo:['Direksiyon','Yol','Pedal']},
    {name:'Bisiklete Binmek', emoji:'🚴', taboo:['Pedal','Tekerlek','Yol']},
    {name:'Diş Fırçalamak', emoji:'🪥', taboo:['Fırça','Ağız','Diş']},
    {name:'Saç Taramak', emoji:'💇', taboo:['Tarak','Saç','El']},
    {name:'Alışveriş Yapmak', emoji:'🛒', taboo:['Market','Para','Sepet']},
    {name:'Temizlik Yapmak', emoji:'🧹', taboo:['Süpürge','Toz','Ev']},
    {name:'Uçurtma Uçurmak', emoji:'🪁', taboo:['İp','Rüzgar','Gökyüzü']},
    {name:'Balık Tutmak', emoji:'🎣', taboo:['Olta','Su','Balık']},
    {name:'Fotoğraf Çekmek', emoji:'📸', taboo:['Kamera','Poz','Işık']}
  ]}

};

const CATEGORY_ORDER = ['hayvanlar','esyalar','sehirler','yiyecekler','ulasim','meslekler','hareketler'];
